name: Pylint

on: push
jobs:
  pylint:
    runs-on: ubuntu-latest
    services:
      pypi_wayback:
        image: ghcr.io/waleko/pypi-wayback
        ports:
        - 8629:8080
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[all]"
        pip install pylint==2.8.2
        pip install pylint-quotes==0.2.3
    - name: Analysing the code with pylint
      run: |
        pylint --load-plugins pylint_quotes sky

env:
  PIP_INDEX_URL: http://localhost:8629/2023-11-07
  UV_INDEX_URL: http://localhost:8629/2023-11-07
